### ISSUE TITLE
foo, bar, etc

### ISSUE THREAD

**Issue by eropple** [eropple/mux-playbackproblems-test#7]
https://example.com/foo.mp4

**Comment by eropple** [comment]
@mux-devex save D5Dkpg

**Comment by eropple** [comment]
@mux-devex save D5Dkpg

**Comment by eropple** [comment]
@mux-devex save D5Dkpg

**Comment by eropple** [comment]
@mux-devex save D5Dkpg

**Comment by eropple** [comment]
@mux-devex save D5Dkpg

**Comment by eropple** [comment]
https://thumbs.gfycat.com/RaggedHeavyKawala-mobile.mp4

**Comment by eropple** [comment]
https://thumbs.gfycat.com/RaggedHeavyKawala-mobile.mp4

**Comment by eropple** [comment]
@mux-devex save g5jV5e

**Comment by eropple** [comment]
@mux-devex save g5jV5e

**Comment by eropple** [comment]
@mux-devex save g5jV5e

**Comment by eropple** [comment]
https://thumbs.gfycat.com/RaggedHeavyKawala-mobile.mp4

**Comment by eropple** [comment]
@mux-devex save 85Qz7Z

**Comment by eropple** [comment]
@mux-devex save 85Qz7Z

**Comment by eropple** [comment]
https://thumbs.gfycat.com/RaggedHeavyKawala-mobile.mp4

**Comment by eropple** [comment]
@mux-devex save D5Dkpg

**Comment by eropple** [comment]
https://thumbs.gfycat.com/RaggedHeavyKawala-mobile.mp4

**Comment by eropple** [comment]
@mux-devex save op2g5E

**Comment by eropple** [comment]
@mux-devex save op2g5E

**Comment by eropple** [comment]
@mux-devex save op2g5E

**Comment by eropple** [comment]
@mux-devex save op2g5E

**Comment by eropple** [comment]
@mux-devex save op2g5E

**Comment by eropple** [comment]
@mux-devex save op2g5E

**Comment by eropple** [comment]
@mux-devex save op2g5E

**Comment by eropple** [comment]
@mux-devex save op2g5E

**Comment by eropple** [comment]
@mux-devex save op2g5E

**Comment by eropple** [comment]
@mux-devex save op2g5E

**Comment by eropple** [comment]
@mux-devex save op2g5E

**Comment by eropple** [comment]
https://thumbs.gfycat.com/RaggedHeavyKawala-mobile.mp4

**Comment by eropple** [comment]
@mux-devex save g5jV5e

**Comment by eropple** [comment]
@mux-devex save g5jV5e

**Comment by eropple** [comment]
@mux-devex save g5jV5e

**Comment by eropple** [comment]
@mux-devex save g5jV5e

**Comment by eropple** [comment]
@mux-devex save g5jV5e

**Comment by eropple** [comment]
@mux-devex save D5Dkpg

**Comment by mux-devex** [comment]
Unfortunately, trying to archive https://thumbs.gfycat.com/RaggedHeavyKawala-mobile.mp4 failed with the following error:

```No such object: playbackproblems/D5Dkpg.mp4
```

If this doesn't look fatal, you can try to save this again with the command `@mux-devex save D5Dkpg`. Reach out to Mux DevEx if you've got any questions!

**Comment by eropple** [comment]
@mux-devex save g5jV5e

**Comment by eropple** [comment]
https://thumbs.gfycat.com/RaggedHeavyKawala-mobile.mp4

**Comment by eropple** [comment]
https://thumbs.gfycat.com/RaggedHeavyKawala-mobile.mp4

**Comment by eropple** [comment]
https://thumbs.gfycat.com/RaggedHeavyKawala-mobile.mp4

**Comment by eropple** [comment]
https://thumbs.gfycat.com/RaggedHeavyKawala-mobile.mp4
